services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    restart: always
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS_ENABLE=true
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  mongo:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - default

  sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sql-container
    restart: always
    ports:
      - "14333:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=$tr0ngS@P@ssw0rd02
      - MSSQL_PID=Express
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  mongodb_data_container:
    driver: local
  sql_data:
    driver: local

networks:
  default:
    name: mydockernetwork
    external: true
